### ISSUE TITLE
bogus files in 1.02

### ISSUE THREAD

**Issue by toddr** [shawnlaffan/perl-alien-sqlite#1]
Your tarball currently includes redundant files  Alien-sqlite-1.02 and Alien-sqlite-1.02.tar and Alien-sqlite-1.02.tar.gz

**Comment by shawnlaffan** [comment]
Thanks for reporting.  I'll fix the MANIFEST.SKIP file and upload a new version in the next few days or so.

**Comment by shawnlaffan** [comment]
Or maybe faster than a few days.  1.03 is now on CPAN.
