### ISSUE TITLE
Installing Alien-sqlite-1.06.tar.gz failed

### ISSUE THREAD

**Issue by Otoliths** [shawnlaffan/perl-alien-sqlite#4]
Hi [shawnlaffan](https://github.com/shawnlaffan),

how to fix it?

cpanm (App::cpanminus) 1.7046 on perl 5.030003 built for MSWin32-x64-multi-thread
Work directory is C:\Users\admin/.cpanm/work/1663394287.5008
You have make C:\Strawberry\c\bin\gmake.exe
You have LWP 6.46
Falling back to Archive::Tar 2.38
--> Working on https://cpan.metacpan.org/authors/id/S/SL/SLAFFAN/Alien-sqlite-1.06.tar.gz
Fetching https://cpan.metacpan.org/authors/id/S/SL/SLAFFAN/Alien-sqlite-1.06.tar.gz
-> OK
Unpacking Alien-sqlite-1.06.tar.gz
Entering Alien-sqlite-1.06
Checking configure dependencies from META.json
Checking if you have Alien::Build::Plugin::Cleanse::BuildDir 0 ... Yes (0.06)
Checking if you have Alien::Build::MM 1.41 ... Yes (2.68)
Checking if you have Sort::Versions 0 ... Yes (1.62)
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.46)
Checking if you have Alien::MSYS 0 ... Yes (0.15)
Checking if you have PkgConfig 0 ... Yes (0.23026)
Checking if you have Alien::Build 1.41 ... Yes (2.68)
Checking if you have File::Find::Rule 0 ... Yes (0.34)
Configuring Alien-sqlite-1.06
Running Makefile.PL
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::PP
Downloaded version is not yet defined
Alien::Build> error in probe (will do a share install): package sqlite3 not found at C:/Strawberry/perl/site/lib/Alien/Build/Plugin/PkgConfig/PP.pm line 89.
Alien::Build> Don't panic, we will attempt a share build from source if possible.
Alien::Build> Do not file a bug unless you expected a system install to succeed.
Checking if your kit is complete...
Looks good
Generating a gmake-style Makefile
Writing Makefile for Alien::sqlite
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have FFI::CheckLib 0.23 ... Yes (0.27)
Checking if you have Archive::Tar 0 ... Yes (2.38)
Checking if you have Mojo::DOM58 1.00 ... Yes (3.001)
Checking if you have Alien::Build::Plugin::Cleanse::BuildDir 0 ... Yes (0.06)
Checking if you have URI::Escape 0 ... Yes (3.31)
Checking if you have IO::Zlib 0 ... Yes (1.10)
Checking if you have IO::Socket::SSL 1.56 ... Yes (2.068)
Checking if you have URI 0 ... Yes (1.76)
Checking if you have Net::SSLeay 1.49 ... Yes (1.88)
Checking if you have Sort::Versions 0 ... Yes (1.62)
Checking if you have HTTP::Tiny 0.044 ... Yes (0.076)
Checking if you have Alien::Build::MM 1.41 ... Yes (2.68)
Checking if you have File::Find::Rule 0 ... Yes (0.34)
Checking if you have Mozilla::CA 0 ... Yes (20200520)
Checking if you have Alien::Base 1.41 ... Yes (2.68)
Checking if you have Alien::Build 1.41 ... Yes (2.68)
Checking if you have PkgConfig 0.19026 ... Yes (0.23026)
Checking if you have Test::Alien 0 ... Yes (2.68)
Checking if you have Alien::MSYS 0.07 ... Yes (0.15)
Checking if you have ExtUtils::MakeMaker 6.52 ... Yes (7.46)
Building and testing Alien-sqlite-1.06
cp lib/Alien/sqlite.pm blib\lib\Alien\sqlite.pm
"C:\Strawberry\perl\bin\perl.exe" -MAlien::Build::MM=cmd -e prefix site C:\STRAWB~1\perl\lib C:\STRAWB~1\perl\site\lib C:\STRAWB~1\perl\vendor\lib
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::PP
Downloaded version is not yet defined
main> prefix C:/STRAWB~1/perl/site/lib/auto/share/dist/Alien-sqlite
"C:\Strawberry\perl\bin\perl.exe" -MAlien::Build::MM=cmd -e version 1.06
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::PP
Downloaded version is not yet defined
"C:\Strawberry\perl\bin\perl.exe" -MAlien::Build::MM=cmd -e download
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::PP
Downloaded version is not yet defined
Alien::Build::Plugin::Core::Download> downloaded sqlite-autoconf-3310100.tar.gz
"C:\Strawberry\perl\bin\perl.exe" -MAlien::Build::MM=cmd -e build
Path::Tiny paths require defined, positive-length parts at C:/Users/admin/.cpanm/work/1663394287.5008/Alien-sqlite-1.06/alienfile line 140.
Alien::Build::Plugin::PkgConfig::Negotiate> Using PkgConfig plugin: PkgConfig::PP
Downloaded version is not yet defined
gmake: *** [Makefile:1036: _alien/mm/build] Error 2
-> FAIL Installing https://cpan.metacpan.org/authors/id/S/SL/SLAFFAN/Alien-sqlite-1.06.tar.gz failed. See C:\Users\admin\.cpanm\work\1663394287.5008\build.log for details. Retry with --force to force install it.

**Comment by shawnlaffan** [comment]
Hello @Otoliths - thanks for the report.  

This should be fixed by https://github.com/shawnlaffan/perl-alien-sqlite/commit/0d6cb8d059cba95ba7b83d0d4f8249767008dda0 

Can you try installing from Github?
```cpanm https://github.com/shawnlaffan/perl-alien-sqlite.git```

If that works then I'll push a new release to CPAN.

**Comment by shawnlaffan** [comment]
Version 1.07 is now on CPAN.  

Thanks again for the report.  If you find any more problems then please open new issues.
